### ISSUE TITLE
Add What3Words as a provider

### ISSUE THREAD

**Issue by DenisCarriere** [DenisCarriere/geocoder#102]
**URL Request**
http://api.what3words.com/w3w?key=API_KEY&string=footloose.sunburnt.tower

**API Docs**
https://what3words.com/api/reference#m1

**Comment by karanparikh** [comment]
Is anyone working on this issue? If not I would like to contribute.

**Comment by DenisCarriere** [comment]
Hey Karan,


At the moment there isn't anyone working on it, I'm currently going down
the list of issues and tackling them one by one.

If you want to send a Pull Request with your changes I will gladly accept
it.

Thanks!

- Denis

*~~~~~~*

*Twitter: @DenisCarriere*
*GitHub: DenisCarriere*

**Comment by karanparikh** [comment]
Thanks for the quick response @DenisCarriere. I will try to send out a pull request within the next 2-3 days.

**Comment by DenisCarriere** [comment]
Well if you want, I can work on it right now.

I'm already in the groove and I've just finished adding Baidu, I can hop
over to w3w next.

You could run a few tests and tell me if it works properly.

I should be able to add w3w in about 2-3 hours max

*~~~~~~*

*Twitter: @DenisCarriere*
*GitHub: DenisCarriere*

**Comment by karanparikh** [comment]
Hi @DenisCarriere there is no hurry from my side. I thought it would be a cool feature to add which is why I volunteered to contribute.

**Comment by DenisCarriere** [comment]
Thanks Karan, adding new providers can be a bit tricky, but once they are added it's easy to maintain. If you could test what3words and make sure it works properly that would be a huge help! :)

**Comment by DenisCarriere** [comment]
You want to check out the docs and test out w3w:

https://geocoder.readthedocs.org/en/latest/providers/W3W/
