### ISSUE TITLE
Custom OSM Server url

### ISSUE THREAD

**Issue by DenisCarriere** [DenisCarriere/geocoder#107]
Question from Twitter:

[@bhosmer](https://twitter.com/bhosmer) [@DenisCarriere](https://twitter.com/DenisCarriere) [@pycoders](https://twitter.com/pycoders) Thanks for the addition of OSM. It would be nice if I could use my own OSM server too.

https://twitter.com/bhosmer/status/561371298509885442

**Comment by DenisCarriere** [comment]
Using your own OSM Server, you should be able to input your own `url` as parameter and Nominatim should function the same way. More testing needs to be done to close this issue

```python
>>> g = geocoder.osm('11 Wall Street, New York', 
                  url='http://nominatim.openstreetmap.org/search')
```

**Comment by benhosmer** [comment]
Thanks for the really quick response. My OSM server isn't running nominatim, it just has tiles, but as soon as I have a chance, I'll get it up there so I can test this. +1 for this!

Incidentally, 

    >>> g =  geocoder.osm('11 Wall Street, New York', url='http://myurlhere.com')
    >>> g.latlng
    []
    >>>> print g
    <[ERROR - URL Connection] Osm - Geocode>

Doesn't give me an error message,

**Comment by DenisCarriere** [comment]
The code isn't suppose to raise an error when there is no response, however the `status` & `error` will result in the error message.
```python
>>> g =  geocoder.osm('11 Wall Street, New York', url='http://myurlhere.com')
>>> g.error
'ERROR - URL Connection'
>>> g.url
'http://myurlhere.com/?q=11+Wall+Street%2C+New+York&addressdetails=1&limit=1&format=json'
```
Not raising an error every time a server does not respond you with the correct geocoding result makes it easier to run bulk geocoding processes.

Another attribute that is included is `ok` which will return `True` or `False` if the result was good or not.

```python
>>> g.ok
False
```

**Comment by benhosmer** [comment]
Thanks for the insight. That makes sense.

**Comment by DenisCarriere** [comment]
I'm not a big fan of `Raise Error` I've been told I code like a Ruby programmer
