### ISSUE TITLE
More intuitive short/long name?

### ISSUE THREAD

**Issue by patrickyan** [DenisCarriere/geocoder#111]
I just recently updated my geocoder version, and it seems like the short/long names are used differently. 

Normally an address like `10 w 10th st, new york, ny` should give a route of `W 10th St`, city of `New York`, and state of `NY`. But with the new defaults, I get `West 10th Street`, `New York`, and New York`. Adding `short_name=True` is no good, cause now I get `W 10th St`, `NY`, `NY`. 

For almost all purposes, addresses are written with route and state as the short name and city as the long name. Currently, the only way to get this combination is by doing using `short_name` for some attributes and then doing `self.address_city = g.parse['locality'].get('long_name')` (figured out this syntax by looking in geocoder source code) for the city. Even if it was just making attributes like `state_short`/ `city_long` or something, it would be a lot easier.

**Comment by DenisCarriere** [comment]
I do agree with your comment, I think that adding the extra long name attribute would be best instead of including the `short_name` parameter as True or False.
I'll update the code to reflect Short Name as the default and Long Name will be an extra attribute.
Thanks for the issue

**Comment by DenisCarriere** [comment]
@patrickyan I've updated the Github Repo, test it out by installing it from Github or when the PyPi 1.1.2 version gets released.
The default is now retrieving the Short Name from Google
These are the only attributes that have differences in the Long vs Short names:
- `road_long`
- `city_long`
- `state_long`
- `country_long`
