### ISSUE TITLE
Convert Housenumber to Integers if possible

### ISSUE THREAD

**Issue by DenisCarriere** [DenisCarriere/geocoder#112]
```python
try:
    return int(housenumber)
except:
    return housenumber
```

**Comment by themiurgo** [comment]
Why this? It seems a complication rather than a desirable feature.

I understand what you want to do is save the hassle of casting:

    response.housenumber # This
    int(response.housenumbr) # rather than this other

However, with this modification I won't know for sure whether the function will return an int or a str and I'll be forced to cast anyways when I call it!

**Comment by DenisCarriere** [comment]
That's true that not knowing if the value would be a int or string can be a
bit tricky for other applications.
I'll undo those changes and change them all to strings as the output
