### ISSUE TITLE
Graceful exit when piping to invalid command

### ISSUE THREAD

**Issue by themiurgo** [DenisCarriere/geocoder#114]
$ geocode -p Google "New York, US" | jq .{lat,lng}
    jq: .lng: No such file or directory
    close failed in file object destructor:
    sys.excepthook is missing
    lost sys.stderr

**Comment by DenisCarriere** [comment]
Odd, I'll look into it when I get a chance

**Comment by DenisCarriere** [comment]
I've looked into this issue, I've got something working right now.

```bash
$ geocode "New York, US" | jq '{lat,lng}'
{
  "lng": -73.83170318603516,
  "lat": 40.78200149536133
}
```
You can also change the name of the keys by doing

```bash
$ geocode "New York, US" | jq '{latitude: .lat,longitude: .lng}'
{
  "longitude": -73.83170318603516,
  "latitude": 40.78200149536133
}
```
Does this solve this issue?

**Comment by themiurgo** [comment]
Yes, it was an error in my jq.

However the problem remains if you provide any invalid command.

    $  geocode "New York, US" | command_that_does_not_exists
    zsh: command not found: command_that_does_not_exists
    close failed in file object destructor:
    sys.excepthook is missing
    lost sys.stderr

In general I don't think any CLI program should give that error. For example ls does not.
    
    $  ls | command_that_does_not_exists
    zsh: command not found: command_that_does_not_exists

**Comment by DenisCarriere** [comment]
Ok so I did some major code refactoring for the CLI, I've added back the Click dependency, it makes the code look so much nicer and makes the `--help` a lot stronger with the choice options.

You should be able to input multiple textfiles + single inputs all at once.

```bash
$ geocode "textfile.txt" "Ottawa, ON" "textfile.txt" --provider google
```
It simply appends all of the content at first and then geocodes them.

Also I removed that Piping error that was occurring by simply catching it with a Try and `sys.exit` after 

If you can test it out to see if it works on your side.

**Comment by themiurgo** [comment]
Yes, it works! :+1:

**Comment by DenisCarriere** [comment]
Sweet :) I'm getting the hang of this CLI now... you made me a big fan of these little awesome programs :+1:
