### ISSUE TITLE
Is it possible to support Yandex Maps API?

### ISSUE THREAD

**Issue by max-arnold** [DenisCarriere/geocoder#117]
Documentation:

http://api.yandex.com/maps/doc/geocoder/desc/concepts/input_params.xml
https://tech.yandex.ru/maps/doc/geocoder/desc/concepts/input_params-docpage/

**Comment by DenisCarriere** [comment]
It shouldn't be a problem to add that, the documentation is well written.

**Comment by DenisCarriere** [comment]
Hey Max,
I've added Yandex as a provider.
Try it out by following the docs here:
https://geocoder.readthedocs.org/en/latest/providers/Yandex/

**Comment by max-arnold** [comment]
Thanks a lot!
