### ISSUE TITLE
Google SSL error

### ISSUE THREAD

**Issue by DenisCarriere** [DenisCarriere/geocoder#123]
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by DenisCarriere** [comment]
I'm using an older version of Python... upgrading Python solves this issue. Derr..

**Comment by Chartres** [comment]
For posterity, this issue was fixed for me after updating package 
```requests:  2.4.1-py27_0 --> 2.5.3-py27_0```
by running
```conda update python``` in Anaconda.

**Comment by DenisCarriere** [comment]
Thanks Chartres for the clear description
