### ISSUE TITLE
How we can update API URL and Keys ?

### ISSUE THREAD

**Issue by singabhi** [DenisCarriere/geocoder#132]
Hi,

I have developer keys and api url for here.

How can update it, with reupdating everytime geocoder lib get updated.

**Comment by DenisCarriere** [comment]
Hey Singabhi,

Have you been to the HERE docs for the geocoder:

http://geocoder.readthedocs.org/en/latest/providers/HERE/

It shows you how to add the developer app_id & app_code.

Can you explain what you mean by api url and how you can update it? From my understanding there's only a single URL for their service.

**Comment by singabhi** [comment]
Thanks Denis for the update.

I have two improvement request for this library:
1. Geocoder sevice can be access by passing complete address as this
library does or by passing qualified values like street, city, state,
postalCode and country. We should update it to handle it.
2. If this library is used by a person who has enterprise version of a
geocoder then he may get different geocoder url to access the service like
i have for HERE. Then in that case he should be able to pass his URL to
your library.

I have sample code updated for above 2 changes. If you agree then i will
share it with you for review.

Thanks and regards
Abhishek Singh

**Comment by DenisCarriere** [comment]
Those improvements sound good.

I don't have a HERE enterprise account so it's hard for me to test that out, but go ahead with the changes and I'll look at them when you do your pull request.

Cheers,

**Comment by singabhi** [comment]
HI Denis,
I made the pull request https://github.com/DenisCarriere/geocoder/pull/139. but this page show " This branch has failed checks, but can be merged."
I am new to Github, please let me know what need to be done to fix the issue.

**Comment by DenisCarriere** [comment]
Hey Abhishek,
Thanks for the pull request, no worries about the fail, sometimes it's geocoding providers that don't seem to work anymore and it's breaking because of that.
I know that I have a lot of work to do with HERE, thanks for the update!
Cheers,
- Denis
