### ISSUE TITLE
Can I get the whole boundary coordinates of a region ?

### ISSUE THREAD

**Issue by bismoy2013** [DenisCarriere/geocoder#133]
Whenever we type some area , eg, New York City , Google maps display a red lined polygon covering the whole area of New York , I wonder if can get the all boundary coordinates of that city or region if I want to using this geocoder . Hope someone will get back soon .

Ref : http://www.quora.com/How-do-I-fetch-the-boundary-coordinates-for-a-region-just-like-the-way-Google-map-displays-whenever-we-search-for-a-region-or-place-in-a-red-lined-polygon-shape

**Comment by DenisCarriere** [comment]
At the moment it's not possible, but I'll look into it.

I'm currently really busy at the moment, if anyone has time, I'll accept
the pull requests.

Denis Carriere
Canadian Forces
GIS Project Manager
OP Renaissance Nepal 2015
OSM: @DenisCarriere
Twitter: @DenisCarriere
Email: Carriere.Denis@gmail.com

**Comment by bismoy2013** [comment]
Thanks for your prompt response . Wonder if there are any other ways / Google API / Mapbox api to fetch those boundary coordinates if we want . Also the documentation of geocoder is very limited , would be useful if someone can make the documentation more descriptive . 

Thanks ! :)

**Comment by Srinucnu** [comment]
Hi @bismoy2013 got solution for this?

**Comment by DenisCarriere** [comment]
Nothing at the moment solves this, I don't know of any providers that provide the geometry of the feature you are geocoding. Maybe Nominatim might have it, but it's not added if that's true

**Comment by MuhammadHasher** [comment]
@bismoy2013 did you find solution of that question ? if so please also help me about the solution of same problem

**Comment by MuhammadHasher** [comment]
@bismoy2013 did you find solution of that question ? if so please also help me about the solution of same problem

**Comment by DenisCarriere** [comment]
Nothing available, you could use the a service likehttps://overpass-turbo.eu to query the boundary of a city or county if it's available in OSM.
