### ISSUE TITLE
geojson method throwing a TypeError

### ISSUE THREAD

**Issue by Mattsface** [DenisCarriere/geocoder#134]
g = geocoder.google("New York City")
/home/mspah/Python/training.python_web/resources/session07/soupenv/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

 g.geojson
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mspah/Python/training.python_web/resources/session07/soupenv/lib/python2.7/site-packages/geocoder/base.py", line 300, in geojson
    feature['bbox'] = self.westsouth + self.eastnorth
TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

**Comment by DenisCarriere** [comment]
Thanks for noticing this bug, I've fixed the issue and uploading a new version to PyPi (Geocoder 1.4.0)

Don't hesitate to report any more bugs in the future.

Cheers!

**Comment by Mattsface** [comment]
Thanks Denis! I was going to make a pull request but you beat me to it :)
