### ISSUE TITLE
Here geocoder returns "Permission Error"

### ISSUE THREAD

**Issue by Chartres** [DenisCarriere/geocoder#135]
The [free HERE Geocoder plan seems to be gone](https://developer.here.com/get-started#/10134037). All geocoding requests return a Permission Error, unless you have a paid license (probably).

**Comment by DenisCarriere** [comment]
That is true, unless HERE offers a free API, this will only work with a valid API key

**Comment by Chartres** [comment]
I can confirm the geocoder works well with valid app_id/app_code from HERE.

**Comment by DenisCarriere** [comment]
I've added a new HERE Key in the latest build 1.5.1, should be valid for the next 3 months
