### ISSUE TITLE
Errors shall throw exceptions instead of sys.exit()

### ISSUE THREAD

**Issue by rublinetsky** [DenisCarriere/geocoder#137]
Try running 
`geocoder.timezone("463a Hong Bang, P14, Q5")`

This throws an error, which results in program's stop. It is impossible to catch it via try/except, because there is no exception - the code simply does `sys.exit()`. E.g. https://github.com/DenisCarriere/geocoder/blob/master/geocoder/location.py#L98

It is a deal-breaker when processing long list of locations...

Could you please change all errors to throwing exceptions instead of exiting?

**Comment by yedpodtrzitko** [comment]
I just stumbled upon the same problem, so +1 for this.

I also grepped a few of your other repos, and it looks like you use this "pattern" quite often. Please dont - learn how to use exceptions instead.

**Comment by DenisCarriere** [comment]
I agree with you both, raising an error is better then `sys.exit`.
Thanks for the improvements guys!
