### ISSUE TITLE
City not parsed correctly from google in some cases

### ISSUE THREAD

**Issue by Chartres** [DenisCarriere/geocoder#140]
Hi there,
Can we include 'postal_town' as a fallback value for city/city_long, when 'locality' is not returned from Google? For example, 'Ullared' is not a 'locality' but a 'postal_town'. See below:
![2015-07-01 15_05_21-ipython py 2 7](https://cloud.githubusercontent.com/assets/4778303/8455360/54d2e42a-2004-11e5-993f-7b386e2862c7.png)
Similarly Southampton here:
![2015-07-01 15_27_07-ipython py 2 7](https://cloud.githubusercontent.com/assets/4778303/8455547/cf21b8e0-2005-11e5-8694-22b7d4488100.png)

Thanks!

**Comment by DenisCarriere** [comment]
Good catch, it looks like this issue would only happen in the UK, I don't think any other countries have `postal_town` as an attribute.
Let me know if it works, it should be fixed now.
