### ISSUE TITLE
URL Connection error

### ISSUE THREAD

**Issue by 37dTY9** [DenisCarriere/geocoder#145]
Hi,

I'm trying to use geocoder but I always get an error.  I get a status of "ERROR - URL Connection". I'm running this in Google App Engine.

No matter whether I try Yahoo, OSM or Google I get the same error.

        g = geocoder.google("41.1474794 -8.55558", key="ABC-MyKey-XYZ", method="reverse")
        logging.info("ok: " + str(g.ok))
        logging.info("status: " + str(g.status))

Any help would be appreciated!

**Comment by DenisCarriere** [comment]
Humm... It seems to work on my side.

I've created a new Google App engine and in the **APIs & auth** tab I searched for **Geocoding API** and enabled it, maybe you didn't do that and it's preventing the connection.

**Comment by 37dTY9** [comment]
I found the issue.  The code is capturing all exceptions and reporting them as URL Connection issues.  I commented that out and found that Python was unable to load the SSL module... I was able to correct that.  You might want to capture the message of the exception or report it as "Unhandled Exception" instead of reporting it as a connection issue when that isn't always the issue.

Thanks for the great package and quick response!

**Comment by DenisCarriere** [comment]
I'm not an expert at catching errors :) Most of the Raised exceptions were submitted by others. Do you mind sending a fix with a pull request for what you are mentioning.

I think you are talking about the **base.py** file at around these lines:

I'm not too sure how someone can catch the SSL module not being loaded, I've never received that error before.

```python
    def _connect(self, **kwargs):
        self.status_code = 'Unknown'
        self.timeout = kwargs.get('timeout', 5.0)
        self.proxies = kwargs.get('proxies', '')
        try:
            r = self.rate_limited_get(
                self.url,
                params=self.params,
                headers=self.headers,
                timeout=self.timeout,
                proxies=self.proxies
            )
            self.status_code = r.status_code
            self.url = r.url
            self.content = r.json()
        except KeyboardInterrupt:
            sys.exit()
        except:
            self.status_code = 404
            self.error = 'ERROR - URL Connection'

        # Open JSON content from Request connection
        if self.status_code == 200:
            try:
                self.content = r.json()
            except:
                self.status_code = 400
                self.error = 'ERROR - JSON Corrupted'
                self.content = r.content
```
