### ISSUE TITLE
Add ArcGIS Reverse geocoding

### ISSUE THREAD

**Issue by DenisCarriere** [DenisCarriere/geocoder#154]
https://developers.arcgis.com/rest/geocode/api-reference/geocoding-reverse-geocode.htm

**Comment by stirringhalo** [comment]
Also very interested in this. I added in the ArcgisReverse function (and modified options in api.py) but no avail. Haven't gone much deeper into diagnosing this yet.

**Comment by DenisCarriere** [comment]
Ok well don't hesitate to send a pull request when it's all ready. :+1:

**Comment by stirringhalo** [comment]
I have these two pull requests to add support: https://github.com/stirringhalo/geocoder/commit/aa7c3a796ee70edb248dfed085069abf48b7ea4c#diff-d7bf54d0ff7e303553f9a5e9a5b27706 and https://github.com/stirringhalo/geocoder/commit/e524b943245f30ffd1647f6a3c0bf77b1498b2db#diff-d7bf54d0ff7e303553f9a5e9a5b27706 .

I think I have everything working as it should. Feel free to clean up any coding style issues. I had to reverse the lat and lon for the queries as ArcGIS needed it in the reverse format to the others.

**Comment by ebreton** [comment]
I think we can close this issue. Arcgis reverse method is here, and functionnal 👍
