### ISSUE TITLE
Baidu Geocoder returns BD-09 geographic coordinate

### ISSUE THREAD

**Issue by chihchun** [DenisCarriere/geocoder#155]
The current Baidu provider[1] returned BD-09[2] coordinate (which encrypted GCJ-02 aka Mars Coordinates)[3], so it only works with Baidu Maps.

It would be nice to address it in the document[1]. Or even better if we put a translator in the module to convert it back to WGS-84 datums as the other geocoder provider.

[1] Baidu — geocoder 1.6.4 documentation http://python-geocoder.org/providers/Baidu.html
[2] Baidu Maps https://en.wikipedia.org/wiki/Baidu_Maps
[3] https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China#BD-09
- 火星坐标系统_百度百科 http://baike.baidu.com/view/3163334.htm

**Comment by DenisCarriere** [comment]
Awesome stuff, thanks for the information, I'll try to find an easy solution for this.

**Comment by ebreton** [comment]
From the code, Baidu takes into account the desired type of coordinates. 

With default `coordtype = kwargs.get('coordtype', 'wgs84ll')`

Closing the ticket :)
