### ISSUE TITLE
Add Mapzen provider

### ISSUE THREAD

**Issue by DenisCarriere** [DenisCarriere/geocoder#156]
https://gist.github.com/sbma44/c005070ac76ece6aa259

**Comment by stirringhalo** [comment]
I'll have a couple pulls tonight for this one.

**Comment by stirringhalo** [comment]
Question Denis, I have Mapzen mostly working. However, when it fails to find a search result, the API returns:

{"type":"FeatureCollection","features":[],"date":1445969167316}

I'm not sure how best to handle this in mapzen.py (https://raw.githubusercontent.com/stirringhalo/geocoder/master/geocoder/mapzen.py). It ends up crashing on getattrs later on. I see Yandex.py needs similar handling but I cannot figure out how it does so.

Thanks!

**Comment by DenisCarriere** [comment]
@stirringhalo Perfect thanks! I'm going time to review it, so whenever that pull request comes in I will make sure it works.

**Comment by ebreton** [comment]
It looks like Mapzen works now. At least, the tests are passing for geocoding, reverse and multiple results 👍 

Closing the ticket !
