### ISSUE TITLE
Autocomplete Geocoders

### ISSUE THREAD

**Issue by kvlahromei** [DenisCarriere/geocoder#157]
Hi, some geocoders support an text autocomplete while a user enters e.g. an address. For example [photon](http://photon.komoot.de/) which is an extended nominatim.

It would be nice if this feature could be used with this lib. Maybe an additional call, or extending the current methods.
Attention: Most geocoder services don't allow  an emulation of this features by permanent polling their API endpoints (e.g. [OSM Nominatim](https://wiki.openstreetmap.org/wiki/Nominatim_usage_policy))

**Comment by DenisCarriere** [comment]
I really like this Photon, some one had mentioned this provider to me, I'll start by adding this provider. I don't really know how autocomplete will work within Python.. but it's worth a shot!

**Comment by kvlahromei** [comment]
Hi, thanks for your investigations. I'm also not sure how to implement it, but maybe it's just an ```guessAdress(input)``` where the geocoders can return an weighted list of possible useful addresses

**Comment by ebreton** [comment]
Hi @kvlahromei ,

I feel sorry that your suggestion did not give birth to features. I have just closed #159 given that is been quite a while now and no one volunteered for the task. 

Doing the same here ...
