### ISSUE TITLE
OpenLS API support

### ISSUE THREAD

**Issue by kvlahromei** [DenisCarriere/geocoder#159]
Hi, the OGC descripes in [Open Location Service 1.2](http://www.opengeospatial.org/standards/ols) - Location Utility Service also an general API for (reverse)geocoding. There are some servers which already implement this standard:
- [OpenRouteService](https://wiki.openstreetmap.org/wiki/OpenRouteService)
- ArcGIS server (using [this connector](https://github.com/mhogeweg/OpenLS))

You might want to try the [OSM OpenLS Route Service - Testclient](http://openls.geog.uni-heidelberg.de/testing2015/geocoding&help).
This might reduce the workload to add new geocoders if they follow this standard protocol.

**Comment by ebreton** [comment]
Hi @kvlahromei ,

Thanks for you suggestion, and the provided links. Given that is been quite a while now and no one volunteered for the task, I will close the issue.

That should not prevent you from making a PR if you have taken some actions on your side in the meantime 😇
