### ISSUE TITLE
Geocoder and Google

### ISSUE THREAD

**Issue by engheta** [DenisCarriere/geocoder#169]
Anyone aware of changes (presumably on Google's side) since Mon Jan 4 which are now breaking the geocoder.google() method in Geocoder?

**Comment by DenisCarriere** [comment]
Hey Bahman, I've tested the google provider on my computer and restarted the Travis CI build and it seems to work fine. You might have reached the rate limit that Google has, you can only request 2500/requests/day.

https://travis-ci.org/DenisCarriere/geocoder/jobs/100031243#L245

Do you have any errors?

```python
g = geocoder.google("Ottawa, ON")
print g
 <[OK] Google - Geocode [Ottawa, ON, Canada]>
print g.error
''
```

**Comment by ColinRJohnson** [comment]
Exactly what I was going to say Bahman, most likely a rate limit issue, I
am having no issues getting 300 out of 300 rooftops returned just this
minute.

On Tue, Jan 5, 2016 at 4:32 PM, Denis <notifications@github.com> wrote:

> Hey Bahman, I've tested the google provider on my computer and restarted
> the Travis CI build and it seems to work fine. You might have reached the
> rate limit that Google has, you can only request 2500/requests/day.
>
> https://travis-ci.org/DenisCarriere/geocoder/jobs/100031243#L245
>
> Do you have any errors?
>
> g = geocoder.google("Ottawa, ON")print g
>  <[OK] Google - Geocode [Ottawa, ON, Canada]>print g.error''
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DenisCarriere/geocoder/issues/169#issuecomment-169139941>
> .
>



-- 
Colin Johnson
C:703.829.6243 (google voice)
C:434.989.2091 (verizon)
colin.r.johnson@gmail.com

**Comment by engheta** [comment]
It is not a rate limit issue. I am familiar with those, haven't been hitting their API at all lately, and can reproduce the issue with different IP addresses. (I am not using an API key or anything, so I'm guessing the only identifier would be the IP address.) 

It does not come back with any error. In fact, it does not come back at all. I have to terminate the process manually. The traceback is pasted below. It gets stuck at self._connect(). 

All other service providers seem to work fine, by the way. 

/usr/local/lib/python2.7/site-packages/geocoder/base.pyc in _initialize(self, **kwargs)
    116         self.content = None
    117         self.encoding = kwargs.get('encoding', 'utf-8')
--> 118         self._connect(url=self.url, params=self.params, **kwargs)
    119         self._build_tree(self.content)
    120         self._exceptions()

/usr/local/lib/python2.7/site-packages/geocoder/base.pyc in _connect(self, **kwargs)
     91                 self.status_code = 200
     92         except KeyboardInterrupt:
---> 93             sys.exit()
     94         except requests.exceptions.SSLError:
     95             self.status_code = 495

**Comment by DenisCarriere** [comment]
Which python version are you using?? There's some SSL issues with the
versions below 2.7

Try using the latest version of python.

**Comment by DenisCarriere** [comment]
I've updated the Geocoder PyPi version (1.7.1), I've had this type of error before and I fixed it in the pass few Github versions.
```bash
$ pip install geocoder --upgrade
```
Or download the latest version from Github
```bash
$ git clone https://github.com/DenisCarriere/geocoder
$ cd geocoder
$ pip install .
```

**Comment by engheta** [comment]
The upgrade(s) helped. 

Thank you for your prompt response!

**Comment by RebliNk17** [comment]
i have an unlimited quotas per day and 3K RPM in google geocoding 
but for some reason - the geocoding is getting stuck after 2500 requests.

what is the reason for enforcing this rate limit of 2500 it in the code instead of working through with each request header?
