### ISSUE TITLE
Filter query by Country for each provider

### ISSUE THREAD

**Issue by mronoffon** [DenisCarriere/geocoder#170]
Is there a way to default queries by country?

**Comment by DenisCarriere** [comment]
Good question, this type of filter would be based on each individual provider.

Google Geocoding API has these additional parameters that I can include in this module.

Optional parameters in a geocoding request:

> **bounds** — The bounding box of the viewport within which to bias geocode results more prominently. This parameter will only influence, not fully restrict, results from the geocoder. (For more information see Viewport Biasing below.)
> **language** — The language in which to return results. See the list of supported domain languages. Note that we often update supported languages so this list may not be exhaustive. If language is not supplied, the geocoder will attempt to use the preferred language as specified in the Accept-Language header, or the native language of the domain from which the request is sent. Street-level addresses will be returned in the local language, transliterated to a script readable to the user if necessary, observing the preferred language to ensure addresses are readable to both the user and locals. All other addresses will be returned in the preferred language. Address components will all be returned in the same language, which is chosen from the first component. Should names not be available in the preferred language, the closest match will be used.
> **region** — The region code, specified as a ccTLD ("top-level domain") two-character value. This parameter will only influence, not fully restrict, results from the geocoder. (For more information see Region Biasing below.)
> **components** — The component filters, separated by a pipe (|). Each component filter consists of a component:value pair and will fully restrict the results from the geocoder. For more information see Component Filtering, below.
