### ISSUE TITLE
geocoder.base.Base.__repr__ throws UnicodeEncodeError

### ISSUE THREAD

**Issue by jtbraun** [DenisCarriere/geocoder#171]
As far as I can tell, __repr__ in CPython 2.* is required to return a str() object, which geocoder.base.Base.__repr__ currently does.

However, there are lots of queries that result in non-ascii values for self.address, resulting in UnicodeEncodeErrors.  An example:
```python
# -*- coding: utf-8 -*-
import geocoder

def myrepr(self):
    if self.address:
        return u"<[{0}] {1} - {2} [{3}]>".format(
            self.status,
            self.provider.title(),
            self.method.title(),
            self.address
        )
    else:
        return u"<[{0}] {1} - {2}>".format(
            self.status,
            self.provider.title(),
            self.method.title()
        )

g = geocoder.osm('Tokyo, Japan')
try:
    print g
except UnicodeEncodeError:
    print "UNABLE TO ENCODE"
print myrepr(g)
```

Probably the best thing to do would be to filter self.address through some function that generates python-like unicode escape codes for any non-ascii characters, so that the resulting __repr__ can be encoded/printed?

**Comment by DenisCarriere** [comment]
Thanks Jeremy for noticing this, I had given up on supporting both Python2 & Python3 encoding out of frustration, but I remembered the **Six** module had a few tricks up their sleeves to make it work.
