### ISSUE TITLE
geocoder.base.Base should not call sys.exit()

### ISSUE THREAD

**Issue by jtbraun** [DenisCarriere/geocoder#172]
The decision on how to handle a KeyboardInterrupt exception should be left up to the application, not a module.  [geocoder.base.Base._connect()](https://github.com/DenisCarriere/geocoder/blob/master/geocoder/base.py) currently does this:
```python
        except KeyboardInterrupt:
            sys.exit()
```
Which takes the decision on how to handle a KeyboardInterrupt away from the application making use of `geocoder.*`.

**Comment by DenisCarriere** [comment]
I agree, that's a better practice! Thanks!
