### ISSUE TITLE
Opencage provider bug using commandline

### ISSUE THREAD

**Issue by M0dM** [DenisCarriere/geocoder#180]
Hi,

I can't specify my api key using command line gecode command.
See the picture attached.

![opencage_geocoder_bug](https://cloud.githubusercontent.com/assets/1061506/13139153/6d7d8858-d62b-11e5-8d1e-5cacf092914a.png)

M0dM

**Comment by DenisCarriere** [comment]
@M0dM Thanks for spotting that out, I always store my keys as environment variables, but using the `--key` is also a great way to connect using the CLI.

I've added the option `--key` to the CLI, you should be able to use it exactly like you mentioned.

```bash
$ geocode 'San Francisco, CA' --provider opencage --key '<API_KEY>' | jq .
{ ... }
```
