### ISSUE TITLE
<[OVER_QUERY_LIMIT] Google - Geocode>

### ISSUE THREAD

**Issue by bilalmahmood1** [DenisCarriere/geocoder#189]
Hey, I am using your geocoder package to extract zip code information from latitude and 
longitude for my points of interest. I have a total of 8000 plus locations, however, your package returns
query limit ceil. Thus is there a way out of this conundrum. 
Thanks

**Comment by DenisCarriere** [comment]
That's the Google api blocking you, Google has a 2500 request/day limit.
Try looking into another provider or use some kind of cashing for your data.

**Comment by bilalmahmood1** [comment]
Thanks for your feedback. I have now capped my requests and it is all working.
