### ISSUE TITLE
Allow strict mode for geolytica

### ISSUE THREAD

**Issue by dondrake** [DenisCarriere/geocoder#196]
An optional parameter

http://geocoder.ca/?premium_api=1

strict	Optional Parameter for enabling strict parsing of free form location input.	1.

should be supported through this interface.

**Comment by DenisCarriere** [comment]
Added both `strict` & `strictmode`.
If you want to add new params, follow the steps in the git commit.
At the moment they are `if` statements because I do not know if the API will break if param is supplied with blank value.
