### ISSUE TITLE
TGOS provider is invalid.

### ISSUE THREAD

**Issue by virus-warnning** [DenisCarriere/geocoder#198]
TGOS provider return API key error.
This provider works with stateful connection.

**Comment by DenisCarriere** [comment]
@virus-warnning Looks like they added an API key
[TGOS HTTP Request Example](http://gis.tgos.nat.gov.tw/TGLocator/TGLocator.ashx?format=jsonp&input=%E5%8F%B0%E5%8C%97%E5%B8%82%E5%85%A7%E6%B9%96%E5%8D%80%E5%85%A7%E6%B9%96%E8%B7%AF%E4%B8%80%E6%AE%B5735%E8%99%9F&srs=EPSG:4326&ignoreGeometry=false&pnum=1&center=121.03988131371027,23.62757835505314&keystr=87E2DG5W%2F5su2xU8DJhScNEO16hD6zhmnnIt2ukeigQ%3D&jsonp=TGOS.getJSON%5B%27sn0%27%5D)

If you can provide me a URL that still works without an API key I can do it, but right now it's blocking the requests.

**Comment by DenisCarriere** [comment]
Re-open the issue when you find that URL

**Comment by virus-warnning** [comment]
Thanks, I'll fork again.
