### ISSUE TITLE
Recent commit has broken geocodefarm.py

### ISSUE THREAD

**Issue by garymonson** [DenisCarriere/geocoder#201]
Relevant part of my stack trace:

```
  File "/usr/lib/python3.4/site-packages/geocoder/__init__.py", line 36, in <module>
    from geocoder.api import get, yahoo, bing, geonames, mapquest, google, mapbox  # noqa
  File "/usr/lib/python3.4/site-packages/geocoder/api.py", line 31, in <module>
    from geocoder.geocodefarm import GeocodeFarm
  File "/usr/lib/python3.4/site-packages/geocoder/geocodefarm.py", line 10, in <module>
    class GeocodeFarm(Base):
  File "/usr/lib/python3.4/site-packages/geocoder/geocodefarm.py", line 37, in GeocodeFarm
    key = self._get_api_key(geocodefarm_key, **kwargs)
NameError: name 'self' is not defined
```

This happens simply from the following in my code:

`import geocoder`

Breaking commit:

[https://github.com/DenisCarriere/geocoder/commit/ac7e2afa1447648f64c4940a46ec431dbf6b3bfa](https://github.com/DenisCarriere/geocoder/commit/ac7e2afa1447648f64c4940a46ec431dbf6b3bfa)

Breaking diff in `geocoder/geocodefarm.py`:

```
     provider = 'geocodefarm'
     method = 'geocode'
 
+    key = self._get_api_key(geocodefarm_key, **kwargs)
+
     def __init__(self, location, **kwargs):
         self.url = 'https://www.geocode.farm/v3/json/forward/'
-
-        key = kwargs.get('key', geocodefarm_key)
-
         self.params = {
             'addr': location,
             'key': key if key else None,
```

The variable `self` is not defined in the new code (line 37).  I suspect the new line is supposed to go in place of the removed line (i.e. inside the `__init__` function - the same way as was done in `geocoder/geocodefarm_reverse.py`.

**Comment by DenisCarriere** [comment]
Just fixed it 30 seconds ago :) Thanks for the report!

**Comment by garymonson** [comment]
No worries.  Thanks for the fix!
