### ISSUE TITLE
Question: changelog

### ISSUE THREAD

**Issue by keradus** [DenisCarriere/geocoder#202]
Hi !
Great lib !

Is there any changelog for it ?

**Comment by DenisCarriere** [comment]
Thanks, unfortunately I wasn't actively tracking a log of the development other then the git descriptions on the comits.

It's a good idea :)

**Comment by keradus** [comment]
I wanted to see difference between 1.16.3 and 1.17.3, but for that there is no changelog, no releases, no tags, hard to compare changes (even in git like `git log v1.16.3..v1.17.3)
:(

**Comment by DenisCarriere** [comment]
It's a mess! :) That's my fault, thanks for letting me know your comments and concerns.

**Comment by keradus** [comment]
if you would at least make tags it would be super awesome ! anything above that is extra as well, but requires some work.

thanks for understanding !

**Comment by DenisCarriere** [comment]
I've added a description to the 1.17.3, it mostly highlights the difference between  1.16 > 1.17.

https://github.com/DenisCarriere/geocoder/releases/tag/1.17.3

**Comment by DenisCarriere** [comment]
I will try to organise my releases a bit better, at the moment I'm just doing minor maintenance on the project. As long as it doesn't break I'm happy :)

**Comment by keradus** [comment]
great ! Thank you !
