### ISSUE TITLE
US Census Geocoder addition

### ISSUE THREAD

**Issue by DenisCarriere** [DenisCarriere/geocoder#205]
Email from Micheal Slade:

I have just started doing geocoding in Python, primarily trying to use

http://www.census.gov/geo/maps-data/data/geocoder.html

for batch geocoding but haven't been able to retrieve any data.

Any possibility of you adding this one to your set of geocoders?

I think that all the other US geocoders eventually rely on maps, etc from
the Census such as the TIGER maps so it would be a great primary source!

**Comment by DenisCarriere** [comment]
Unfortunately I don't have much time to concentrate on the Python Geocoder, however Pull Requests/contributions are welcomed.

There are a lot of examples in the Python Geocoder source code that will show you how to add a new provider.

**Mapzen**
https://github.com/DenisCarriere/geocoder/blob/master/geocoder/mapzen.py

**Bing**
https://github.com/DenisCarriere/geocoder/blob/master/geocoder/bing.py

**Comment by ebreton** [comment]
USCensus is currently supported (refactored, and tested)

I guess we can close this ticket :-)

If I have missed something, just open it again with a comment !
