### ISSUE TITLE
How to get region border coordinates (polyline) data?

### ISSUE THREAD

**Issue by MuhammadHasher** [DenisCarriere/geocoder#206]
I'm trying to get (specified) region borders as GMaps coordinates (to form a polyline) from Google Maps. Is this possible in some way? (either from maps.google.com).
**NOTE**
 I know you can draw/outline regions manually with tools intended for it (like http://www.birdtheme.org/useful/v3tool.html), but covering a large region ACCURATELY is a ton of work. The draw-it-yourself answer is not an option in this case.

**Example**
1. https://maps.google.com/ -> type in "Ottawa, Canada"
2. You can see the pink-ish border that outlines the wanted region
3. That border is the polyline that I need the coordinates of

**Requirements:**
- Extract the region data coordinates (if available) from a given search (as in the example)
- If the previous is not possible, a source to an ACCURATE map boundaries of the region is required

**Comment by ebreton** [comment]
Hi @MuhammadHasher , geocoder will not be able to return those borders, which are a (long) array of points basically... That's too far fetched from geocoding, which returns one point for an address (or possibly multiple potential results for the given address)

The best we have, as region, is the `bbox`.

You might have a look at those, but is 'only' a rectangle, defined by two corners...
