### ISSUE TITLE
Tomtom Geocode is broken

### ISSUE THREAD

**Issue by ares86** [DenisCarriere/geocoder#207]
Tomtom changed their documentation. The base url is not longer: https://api.tomtom.com/lbs/geocoding/geocode  but instead: https://api.tomtom.com/search/2/geocode/

Then. If I try to use the tomtom provider, it results in a broken api call.

TomTom's documentation: http://developer.tomtom.com/products/onlinenavigation/onlinesearch/documentation/Geocoding/Geocode

**Comment by DenisCarriere** [comment]
Thanks for reporting this, feel free to send a pull request with the appropriate API changes, otherwise I'll have to look at this another day.

**Comment by ebreton** [comment]
will be fixed with PR #288

**Comment by ebreton** [comment]
fixed :)

**Comment by DenisCarriere** [comment]
👍 Very nice!
