### ISSUE TITLE
Mapbox access token

### ISSUE THREAD

**Issue by rjdel** [DenisCarriere/geocoder#212]
Hello, I've added my Mapbox token to the environmental variables of my Mac and am not yet able to access Mapbox because of an API issue.  The key was generated yesterday and I've tested it to make sure it works.

I then added it as a parameter to the script itself and still the same issue.  

Not sure what I'm doing wrong but any help would be great!

Thanks!

Ryan

**Comment by DenisCarriere** [comment]
Strange... must be something wrong with you access token?
I just tested the mapbox provider on my computer right now and it works.

Here are the steps I did:

```bash
$ export MAPBOX_ACCESS_TOKEN=pk.eyJ1IjoiZG5vbWFkYiIs...
$ geocode "Ottawa ON" -p mapbox | jq .
{
  "status": "OK",
  "confidence": 1,
  "ok": true,
  "encoding": "utf-8",
  "country": "Canada",
  "provider": "mapbox",
  "state": "Ontario",
  "bbox": {
    "northeast": [
      45.5369839930512,
      -75.2459327878018
    ],
    "southwest": [
      44.962213116635,
      -76.3539711072854
    ]
  },
  "status_code": 200,
  "address": "Ottawa, Ontario, Canada",
  "lat": 45.421,
  "lng": -75.69,
  "postal": "K2P 0B9",
  "quality": 0.998,
  "location": "Ottawa ON"
}
```

**Comment by rjdel** [comment]
Thanks for the help.  I put it the key in the source and forgot about it.  Sorry to have brought you my error.  Thanks though for responding.  Your geocoder is exactly what I needed thanks for putting it out there.

**Comment by DenisCarriere** [comment]
Awesome! I'm no longer doing maintenance on this library since I'd have to fully re-write the source code to fix many of the existing issues.
I've started a new geocoder library written in Javascript that will essentially do the same thing as this library but with less headaches for me as a developer.

https://github.com/DenisCarriere/geocoder-geojson
