### ISSUE TITLE
Unofficial endpoint for FreeGeoIP causes intermittent errors

### ISSUE THREAD

**Issue by carsonyl** [DenisCarriere/geocoder#215]
In c54c9ad6, the REST endpoint for FreeGeoIP was changed from the official one at http://freegeoip.net/ to https://telize.j3ss.co/geoip/. What was the rationale behind this?

The unofficial endpoint seems to respond inconsistently: sometimes latitude and longitude are strings, and sometimes either latitude or longitude are missing entirely, causing "ERROR - No Geometry" from Geocoder.

**Comment by DenisCarriere** [comment]
Seems like both REST endpoints are unstable, that's why I did the switch.

I guess we could switch it back to freegeoip, that server was blocked last time I was testing it.

Feel free to send a PR with a more stable server.

Thanks for the heads up!

**Comment by ebreton** [comment]
URL set back to freegeoip servers in PR #286  :)

**Comment by ebreton** [comment]
PR merged... closing the issue 👍
