### ISSUE TITLE
Yandex geocoder moved to https

### ISSUE THREAD

**Issue by lavr** [DenisCarriere/geocoder#229]
Each request to yandex geocoder now causing two real requests - first is just for redirect:

    >>> geocoder.yandex(location=['37.61892', '55.756994'], method='reverse')
    INFO 2017-02-05 03:15:33,314 [none] requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): geocode-maps.yandex.ru
    DEBUG 2017-02-05 03:15:33,358 [none] requests.packages.urllib3.connectionpool: "GET /1.x/?lang=en-US&kind=&geocode=37.61892%2C+55.756994&results=1&format=json HTTP/1.1" 301 184
    INFO 2017-02-05 03:15:33,362 [none] requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): geocode-maps.yandex.ru
    DEBUG 2017-02-05 03:15:33,477 [none] requests.packages.urllib3.connectionpool: "GET /1.x/?lang=en-US&kind=&geocode=37.61892%2C+55.756994&results=1&format=json HTTP/1.1" 200 None

According to [API documentation](https://tech.yandex.com/maps/doc/geocoder/desc/concepts/input_params-docpage/) request should always be sent using https.

**Comment by DenisCarriere** [comment]
Thanks for the PR
