### ISSUE TITLE
No documentation for using Sessions in forward-geocoding

### ISSUE THREAD

**Issue by sachinlohith** [DenisCarriere/geocoder#231]
Hello,
    I was going through the documentation [geocoder.readthedocs.io](http://geocoder.readthedocs.io/api.html#using-a-session) and it mentions the usage of session along with geocoder. However, the actual information on how to use sessions is missing.

**Comment by DenisCarriere** [comment]
Send a PR with a fix

**Comment by sachinlohith** [comment]
I have no idea how to use sessions along with geocoder. I just started using the API. If you could let me know how, I'll add the documentation and send you a PR.

**Comment by DenisCarriere** [comment]
Oh I didn't even know it was already in the docs, it looks like @MRigal added it https://github.com/DenisCarriere/geocoder/commit/b248ab6b785585c557db11b1b7b70378bda96b79, however it seems like the Python example didn't properly show up.

Here's the example @MRigal included:

```python
with requests.Session() as session:
    berlin = geocoder.google("Ritterstr. 12, 10969 Berlin", session=session)
    ottawa = geocoder.google("453 Booth Street, Ottawa ON", session=session)
```
