### ISSUE TITLE
Google Forward Geocoding Unhandled Exception

### ISSUE THREAD

**Issue by magiccityanalytics** [DenisCarriere/geocoder#232]
Receiving this in the JSON output when attempting to forward geocode:

![image](https://cloud.githubusercontent.com/assets/26073076/23381861/b19b84b6-fd05-11e6-8abd-9d99a917c85d.png)

Reverse geocoding works fine:

![image](https://cloud.githubusercontent.com/assets/26073076/23381845/a1f44372-fd05-11e6-9364-d3c56808194f.png)

API key and everything are set up properly. API calls from reverse geocoding script show up in Google API dashboard. No API calls recorded in dashboard when the forward script is run.

FWIW the forward and reverse geocoding scripts are nearly identical, and if I remove the API environment variables and everything and use the free API calls that Google allows, both forward and reverse geocoding work fine.

**Comment by DenisCarriere** [comment]
Strange... The Free API seems to work just fine.

Maybe Google changed their API when providing an API key.

PR's are welcomed 👍

**Comment by magiccityanalytics** [comment]
The Free API does work fine, however I need more daily calls than it allows
hence using paid version, which is what I am experiencing issues with.

Joe Spano
Chief Executive Officer
Magic City Analytics

joe@magiccityanalytics.com

+1.205.775.0MCA

www.magiccityanalytics.com

**Comment by magiccityanalytics** [comment]
This issue was resolved by removing the Client ID and Client Secret environment variables.

**Comment by DenisCarriere** [comment]
Oh yes, that might of been the problem.
