### ISSUE TITLE
Google Reverse Geocode Not Adding Signature When Using Client Id

### ISSUE THREAD

**Issue by cotzanium** [DenisCarriere/geocoder#236]
Im trying to use the google reverse geocoder with a client id and client secret. It used to work in the previous version but now its giving me issues. I have checked the generated request and i noticed that its missing the signature.

example:
geocoder.google([latitude, longitude], method='reverse', client='client', client_secret='client secret')

the generated request: https://maps.googleapis.com:443 "GET /maps/api/geocode/json?sensor=false&latlng=-29.81468939999%2C+30.860086100000004&client=client&language= HTTP/1.1"

If i use the googlemaps library the generated request will be: https://maps.googleapis.com:443 "GET /maps/api/geocode/json?latlng=-29.814689%2C30.860086&client=client&signature=signature HTTP/1.1"

**Comment by DenisCarriere** [comment]
@cotzanium Thanks for reporting this, this commit https://github.com/DenisCarriere/geocoder/commit/a491f07cc24caee48e27c716a3f7c421307b8476 should of fixed it.

I personally don't have a Google client/secret key to test this, if this didn't work, please don't hesitate to re-open this issue.
