### ISSUE TITLE
geocoder.ip('me').country returns None

### ISSUE THREAD

**Issue by kizniche** [DenisCarriere/geocoder#250]
Thanks for a great package that's worked in my system, [Mycodo](https://github.com/kizniche/Mycodo), for over a year without an issue.

Recently (past week or so), I've been having the country query return None, from systems around the world.

```python
import geocoder
print("Country='{return}'".format(return=geocoder.ip('me').country))
```

```bash
$ python ./test_geocoder.py
Country='None'
```

I haven't dug enough into geocoder to know exactly how to debug this.

Is this a known issue? Is there anything I can do to help?

**Comment by kizniche** [comment]
Interestingly, not all systems have experienced this issue, even though they are all using the same geocoder version. This leads me to believe whatever service is being queried may be banning IP addresses or something similar.

**Comment by DenisCarriere** [comment]
@kizniche There's two providers that offer reverse IP lookups, `maxmind` & `ipinfo`. Both of them have tradeoffs.

Seems like `geocoder.ip('me')` is broken if you provide 'me' or blank.

```python
>>> geocoder.ip('me')
>>> g.debug()
{}
{
    "status": "Cannot GET //json\n", 
    "status_code": 400, 
    "provider": "ipinfo", 
    "ok": false, 
    "encoding": "utf-8"
}
```

Strange that it use to work before, maybe it was always a "bug" however their server accepted that HTTP request.

**Solution:** Change `geocoder.ip('me')` HTTP request from `http://ipinfo.io//json` => `http://ipinfo.io/json`

**Comment by kizniche** [comment]
Thanks for the timely reply and fix. Just curious, how long do you expect it to be before this fix reaches PyPI?

**Comment by DenisCarriere** [comment]
Oh my bad... I did commit the changes, however PyPi changed their backend and I couldn't easily publish the new release.
Let me see if I can get it to work.

**Comment by DenisCarriere** [comment]
@kizniche Try it now, just published new patch release.

This PyPi migration!! 😠

**Comment by kizniche** [comment]
Working great. It's very much appreciated! Thanks, again.

**Comment by DenisCarriere** [comment]
👍
