### ISSUE TITLE
"ImportError: No module named orderedset" in release 1.24.0

### ISSUE THREAD

**Issue by stefanw** [DenisCarriere/geocoder#258]
The latest release makes use of the package `orderedset` without putting it as a required dependency in `setup.py` and therefore breaks installs.

Possibly travis builds should not install via `requirements.txt` but via `pip install -e .` in order to catch these mistakes.

**Comment by DenisCarriere** [comment]
Oh! my bad.. yes we should try to catch that.

CC: @ebreton

**Comment by DenisCarriere** [comment]
Published `v1.24.1` try that to see if it works now.

**Comment by ebreton** [comment]
true, I did not update the setup.py... ^^

**Comment by DenisCarriere** [comment]
:) all good
