### ISSUE TITLE
updating what3words provider to use API v2

### ISSUE THREAD

**Issue by tsamaya** [DenisCarriere/geocoder#260]
Hi,

I can see the what3words provider is using what3words API v1. 

what do you think about updating to use what3words API v2 ?

here is a commit with the changes https://github.com/tsamaya/geocoder/commit/c14acde44eeab659cd08dbf96befbe8b87252eb5

I added a unit test for what3words and left it commented as I don't know if it will break travis build.

Please let me know what do you think and I can make a PR

**Comment by DenisCarriere** [comment]
👍 Looks good to me, if you could please send over a PR and we can have that merged in the repo.

**Comment by tsamaya** [comment]
thanks PR #261 made

**Comment by ebreton** [comment]
Hi @tsamaya , 

thanks again for the PR 👍 
I have un-commented the tests and everything passes all right in #281 . I have also upgraded the code to make use of the multiple-results support (though I haven't added tests for this, never used w3w...)

I am closing this issue, nevertheless, do not hesitate to make feedback here!
Manu
