### ISSUE TITLE
Install with python 3.5

### ISSUE THREAD

**Issue by Vyasa971** [DenisCarriere/geocoder#272]
I would like to use your package (with Python 3.5) but unfortunately I have some issue, when I tried to launch the command (on Windows) I have the following error : 
 
error: Could not find suitable distribution for Requirement.parse('orderedset')
 
I installed the MS C++ compiler (VS2017) but nothing changed.

**Comment by ebreton** [comment]
Hi @Vyasa971 ,

We have just removed orderedset from the lib, which was indeed breacking the lib on windows)

Could you check that you are using version 1.26.0 ?

**Comment by Vyasa971** [comment]
Perfect ! With the version 1.26.0 
It works like a charm ! 
Thank you for your prompt response ^^
