### ISSUE TITLE
Opencage geocoder circular lookup for Town

### ISSUE THREAD

**Issue by nyejon** [DenisCarriere/geocoder#276]
There is a circular lookup on the Opencage geocoder which makes it unusable. The problem was introduced with merge request: #257 

The following line was changed:

     @property
      def town(self):
          return self.parse['components'].get('town')

to 

     return self.city

The problem is city returns town... and so the circle continues.

I will fix the issue and submit it. While I'm at it I will check that the other aliases are also configured for https://github.com/OpenCageData/address-formatting/blob/master/conf/components.yaml

**Comment by nyejon** [comment]
What is the best behavior for getting a component? Should all aliases return one of the other aliases if it does not exist?

For example:

    @property
    def city(self):
        city = self.parse['components'].get('city')
        if city:
            return city
        elif self.town:
            return self.town
        elif self.village:
            return self.village
        elif self.county:
            return self.county

Will return the town if city does not exist, but:

    @property
    def town(self):
        return self.parse['components'].get('town')

will only return the town if it exists. Should it be changed to:

    @property
    def city_aliases(self):
        town = self.parse['components'].get('town')
        city = self.parse['components'].get('town')
        village = self.parse['components'].get('town')
        county = self.parse['components'].get('town')
        if city:
            return city
        elif town :
            return town 
        elif village:
            return village
        elif county:
            return county

    @property
    def city(self):
        city = self.parse['components'].get('city')
        if city:
            return city
        else:
            return self.city_aliases

**Comment by ebreton** [comment]
@nyejon , thanks again for your PR, the fix and improvements 👍 

I guess we can close the issue, right? Feel free to open it again in any other cases!
Manu

**Comment by DenisCarriere** [comment]
👍
