### ISSUE TITLE
Google - other methods and client keys

### ISSUE THREAD

**Issue by avanderm** [DenisCarriere/geocoder#285]
Hey again,

Will have to bother with another problem I'm afraid. The fix you made for the client keys worked for the Google geocoding method, but the absence of checking for client keys in the other methods (places, ...) causes them to fail (they still work with API keys only). I've looked into it, but haven't made much progress in finding a simple fix yet.

Thanks!

EDIT: been reading up on the Google APIs, Premium plan does not seem to cover Google Places API

**Comment by DenisCarriere** [comment]
? was that fixed or not? Why did you close?
