### ISSUE TITLE
Gaode map can not be used

### ISSUE THREAD

**Issue by yue899889** [DenisCarriere/geocoder#291]
> AttributeError                            Traceback (most recent call last)
> <ipython-input-285-f555424f36e7> in <module>()
> ----> 1 geocoder.gaode
> 
> AttributeError: 'module' object has no attribute 'gaode'

**Comment by ebreton** [comment]
could you provide a bit more context ? like...

- which python version
```
$ python --version
Python 3.6.1
```

- which geocoder version
```
>>> from geocoder import __version__
>>> __version__
'1.32.1'
```

- what call have you done
```
>>> import geocoder.gaode
>>> geocoder.gaode('将台路')
<[OK] Gaode - Geocode [北京市朝阳区将台路]>
```

**Comment by ebreton** [comment]
Hi @yue899889 ,

Could you please if the error still occurs on the branch fix_opencage (PR #294 )

If not: please provide the information I mentioned in my last comment

Cheers
Manu

**Comment by ebreton** [comment]
no news good news?

I am closing the issue but feel free to re-open if you still have the error (with the context please)
