### ISSUE TITLE
429 too many requests response from mapzen

### ISSUE THREAD

**Issue by tombuckley** [DenisCarriere/geocoder#303]
I get 429 too many requests responses from the Mapzen service. Is there some kind of throttling that Mapzen expects? 

cc @rmglennon

example request:
```
def geocode_mapzen(address, maps_api_key):
	return(geocoder.mapzen(address, key=maps_api_key))
```

mapzen seems to see the requests in my quota but they are well below the 25k.

**Comment by DenisCarriere** [comment]
Not too sure how to fix this one, sounds like a Rate limiting issue with Mapzen, try doing an HTTP request to their API directly and see if it's the same behavior.

**Comment by rmglennon** [comment]
With Mapzen APIs, 429 errors typically occur when you exceed:

- monthly free rate limits on a particular service and do not have a payment method on file
- your monthly spending limit
- per-second rate limits. 

By default, geocoding and autocomplete are currently set at 6 requests per second.

**Comment by DenisCarriere** [comment]
Thanks @rmglennon for the quick Mapzen reply, much appreciated! ❤️

**Comment by ebreton** [comment]
closing the issue since we have the answer :alarm_clock:
