### ISSUE TITLE
Improve Open Street Map OSM

### ISSUE THREAD

**Issue by MichaelRazum** [DenisCarriere/geocoder#304]
Hello,

the open street map nomination api provides more detailed querys: http://wiki.openstreetmap.org/wiki/Nominatim

As I understand the project to support this we need a class like that one:
`class OsmQueryDetail(MultipleResultsQuery):
    """
    Nominatim
    =========
    Nominatim (from the Latin, 'by name') is a tool to search OSM data by name
    and address and to generate synthetic addresses of OSM points (reverse geocoding).

    API Reference
    -------------
    http://wiki.openstreetmap.org/wiki/Nominatim
    """
    provider = 'osm'
    method = 'geocode'

    _URL = 'https://nominatim.openstreetmap.org/search'
    _RESULT_CLASS = OsmResult
    _KEY_MANDATORY = False

    def _build_params(self, location, provider_key, **kwargs):
        # backward compatitibility for 'limit' (now maxRows)
        if 'limit' in kwargs:
            logging.warning(
                "argument 'limit' in OSM is deprecated and should be replaced with maxRows")
            kwargs['maxRows'] = kwargs['limit']
        # build params
        query = {
            'format': 'jsonv2',
            'addressdetails': 1,
            'limit': kwargs.get('maxRows', 1),
        }
        query.update(kwargs)
        return query

    def _before_initialize(self, location, **kwargs):
        """ Check if specific URL has not been provided, otherwise, use cls._URL"""
        url = kwargs.get('url', '')
        if url.lower() == 'localhost':
            self.url = 'http://localhost/nominatim/search'
        elif url:
            self.url = url
        # else:  do not change self.url, which is cls._URL`

And adding        
    'osm': {
        'geocode': OsmQuery,
        'detail': OsmQueryDetail,
        'reverse': OsmReverse,
    }

That works fine for me. That is my query that is working now:
geocoder.osm("",postalcode="45326", street="Ellernstrasse", method="detail")

I wanted to make a pull request but it didn't worked. Don't have the rights I guess.

**Comment by DenisCarriere** [comment]
Thanks for the info, definitely agree that the OSM nominatim provider needs an update.

As for making a Pull request, you will need to fork this project and then compare your forked repo to create a pull request.

Lots of help on GitHub to get you started: https://help.github.com/articles/creating-a-pull-request/

**Comment by DenisCarriere** [comment]
👍

**Comment by MichaelRazum** [comment]
Thanks! It worked : ). I created a pull request.

**Comment by ebreton** [comment]
PR #305  merged

🍾 !

**Comment by DenisCarriere** [comment]
Woot! 🎉
