### ISSUE TITLE
geocoder.google vs others?

### ISSUE THREAD

**Issue by snovik75** [DenisCarriere/geocoder#307]
When I am running `geocoder.google('11 Wall Street, New York')` I receive `<[OK] Google - Geocode [11 Wall St, New York, NY 10005, USA]>`

However, when I am running `geocoder.osm('11 Wall Street, New York')` or `geocoder.yandex('11 Wall Street, New York')` I get `Status code Unknown from https://nominatim.openstreetmap.org/search: ERROR - HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=175+5th+Avenue+NYC&format=jsonv2&addressdetails=1&limit=1 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required ( Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied.  )',)))`

How come there is a different treatment of google vs everything else? How can I get osm working as well?

**Comment by DenisCarriere** [comment]
Seems to work for me, looks like it's a network issue on your client side, maybe a firewall is preventing the HTTP requests.

```bash
$ geocode "11 Wall Street, New York" -p google
$ geocode "11 Wall Street, New York" -p osm
```

**results**
```json
{
  "encoding": "utf-8",
  "status_code": 200,
  "place_id": "169621055",
  "county": "Suffolk County",
  "street": "Wall Street",
  "osm_id": "470231498",
  "lng": -73.42776365,
  "quality": "yes",
  "confidence": 10,
  "type": "yes",
  "state": "New York",
  "location": "11 Wall Street, New York",
  "provider": "osm",
  "housenumber": "11",
  "accuracy": 0.511,
  "status": "OK",
  "importance": 0.511,
  "bbox": {
    "northeast": [
      40.8716548,
      -73.4275981
    ],
    "southwest": [
      40.8715761,
      -73.4279292
    ]
  },
  "address": "11, Wall Street, Halesite, Suffolk County, New York, 11743, United States of America",
  "lat": 40.87161545,
  "postal": "11743",
  "ok": true,
  "country": "United States of America",
  "region": "New York",
  "osm_type": "way",
  "place_rank": "30"
}
```
