### ISSUE TITLE
Fail on Yahoo PlaceFinder

### ISSUE THREAD

**Issue by billytotochan** [DenisCarriere/geocoder#311]
I thinks its Yahoo API changed?

Both cli and python API reproduce the same error.
>>> g = geocoder.yahoo('San Francisco, CA')
>>> g.json
Command Line Interface
$ geocode 'San Francisco, CA' --provider yahoo --out geojson

`Traceback (most recent call last):`
`  File "/usr/local/lib/python3.6/site-packages/geocoder/base.py", line 458, in _initialize`
`    json_response) if json_response else True`
`  File "/usr/local/lib/python3.6/site-packages/geocoder/yahoo.py", line 101, in _catch_errors`
`    status = json_response['statusDescription']`
`KeyError: 'statusDescription'`

**Comment by ebreton** [comment]
I think this one is a duplicate of #148 ...

I am closing this one since the other contains more info to upgrade the provider

Please reopen if I did not got it right 🙏

**Comment by Kayden-lolasery** [comment]
@ebreton running the sample code on https://geocoder.readthedocs.io/providers/Yahoo.html fails

It has been 4 years will this be resolved?
![image](https://user-images.githubusercontent.com/78312050/189648267-9f7ee2a9-380e-49e6-8bfe-ad0e7330ef6e.png)

![Capture](https://user-images.githubusercontent.com/78312050/189647308-b71718da-9f6b-4b97-ab4e-282a4ca0ad86.PNG)
