### ISSUE TITLE
Opencage reverse geocoding issue

### ISSUE THREAD

**Issue by nyejon** [DenisCarriere/geocoder#313]
Hi, 

This one had me stumped for quite a while as I had no idea where the problem lay, however I think I have gotten to the bottom of it. There is an error in the _build_params of OpenCageReverse:

The 'query' is using self.location when it should be just location:
 ```
def _build_params(self, location, provider_key, **kwargs):
        location = Location(location)
        return {
            'query': self.location,
            'key': provider_key,
        }
```
The first way causes the request to turn out like this:
https://api.opencagedata.com/geocode/v1/json?query=52.882079&query=11.747445&key=xxx

which returns garbage... I was wondering why my requests were coming back with really odd locations...

 ```
def _build_params(self, location, provider_key, **kwargs):
        location = Location(location)
        return {
            'query': location,
            'key': provider_key,
        }
```

With this, the request looks much better... : 
http://api.opencagedata.com/geocode/v1/json?query=49.973888%2C+8.069823&key=xxx

Not sure if this is the actual root cause, as I haven't followed everything all the way back, but it seems to resolve it for now

**Comment by DenisCarriere** [comment]
👍 Merged in PR
