### ISSUE TITLE
Regression on #248, ability to add custom params and headers

### ISSUE THREAD

**Issue by interDist** [DenisCarriere/geocoder#315]
The logic for `self.params` and `self.headers` is broken... The custom params (in `kwargs`) should be _combined_ with the result of `self._build_params()` but now they are being preferred to the built-in params of the provider, resulting in access forbidden errors, for example (the API key is not sent in the request if a custom param is provided). The same goes for the headers.

The exact locations are: https://github.com/DenisCarriere/geocoder/blob/535feea845fa52ad392d958bdfa95d06c688ddc5/geocoder/base.py#L392-L393 and https://github.com/DenisCarriere/geocoder/blob/535feea845fa52ad392d958bdfa95d06c688ddc5/geocoder/base.py#L388-L389

**Comment by ebreton** [comment]
Hi @interDist ,

Thanks for the heads up! You are right, if present, `params` and `headers` take precedence. Would you push a PR to change this behaviour and combine the two?

Cheers,
Manu

**Comment by ebreton** [comment]
fixed in  PR #323
