### ISSUE TITLE
geonames premium server

### ISSUE THREAD

**Issue by nikolatulechki** [DenisCarriere/geocoder#316]
After purchasing credits from geonames, we are required to use the premium server "ws.geonames.net". There is no straightforward way to change the url within the package.

**Comment by ebreton** [comment]
Hi @nikolatulechki , 

I have added the parameter 'url' to allow you to override the URL to query. Can you make a test on the branch of PR #317 and tell me if that work for you ?

Be aware that you need to pass the full URL of the service you target, ie:

- ```http://ws.geonames.org/searchJSON``` for basic geocoding
- ```http://ws.geonames.org/childrenJSON``` to get children
- ```http://ws.geonames.org/hierarchyJSON``` for hierarchy and so on

Do not hesitate to share feedback, or even suggest changes in the PR

Cheers,
Manu

**Comment by ebreton** [comment]
no news good news 😬
