### ISSUE TITLE
Print errors returns "None"

### ISSUE THREAD

**Issue by Nickstr** [DenisCarriere/geocoder#320]
Im running a simple lambda that takes an address string and returns the lat/long for it. I'm running into the issue that when a service fails to find a lat/long i'm unable to return the error in a usuable way.

```python

    geocoder.osm(event['address'])

    print(type(result))
    <class 'geocoder.osm.OsmQuery'>

    print(result)
    <[ERROR - No results found] Osm - Geocode [empty]>

    print(result.json)
    None
```

**Comment by ebreton** [comment]
Hi @Nickstr ,

Sorry for the delay... I guess you have moved forward, or maybe find an answer to your question ?

If I may, you do not have any error in your example, simply no results. 

Would you have errors, we store them in `result.error` (which will be False in your case)

Closing the issue, but feel free to open it again, I will be happy to help

**Comment by Nickstr** [comment]
No problem at all!

Thanks for the reply!
