### ISSUE TITLE
No module named builtins on python 3.5, django 1.11

### ISSUE THREAD

**Issue by melon-ruet** [DenisCarriere/geocoder#322]
Getting an error

[Tue Dec 26 08:50:51.964620 2017] [wsgi:error] [pid 17383:tid 140268205184768] [remote <ip>:40898]   File "/home/melon/PycharmProjects/virtual/lib/python3.5/site-packages/geocoder/base.py", line 4, in <module>
[Tue Dec 26 08:50:51.964727 2017] [wsgi:error] [pid 17383:tid 140268205184768] [remote <ip>:40898]     from builtins import str
[Tue Dec 26 08:50:51.964750 2017] [wsgi:error] [pid 17383:tid 140268205184768] [remote <ip>:40898] ImportError: No module named builtins

**Comment by ebreton** [comment]
Hi @melon-ruet 

Did you solve your issue ? may be requirements not all installed ?

I am closing the ticket but please fell free to open it again if I can help !
