### ISSUE TITLE
Over query limit issue

### ISSUE THREAD

**Issue by pruthvipatnala** [DenisCarriere/geocoder#326]
It would be better if you could be specific about the reason over "OVER_QUERY_LIMIT" errors , as 
1) The number of requests is unclear
2) The same error is returned for some legitimate place names as well. After the error , I am able to access details of another place in the very next request (though it says "OVER_QUERY_LIMIT").
( It is not covering all places .)

**Comment by ebreton** [comment]
Hi @pruthvipatnala ,

Every provide has its own set of rules when it comes to quotas... and also its own way to raise errors or provide feedback. We addressed it by capturing the errors in the `error` attribute of a result.

We also tried to be as explicit as possible in the documentation, and you will find on the github homepage links to the usage of every provider, in the [Providers table](https://github.com/DenisCarriere/geocoder#providers).

That should help 😇 

You can also check in past issues for more details, like #303 for mapzen, or #189 for google...
