### ISSUE TITLE
Default "fuzzy" parameter value for Geonames

### ISSUE THREAD

**Issue by paramono** [DenisCarriere/geocoder#331]
In Geocoder's wrapper for Geonames "fuzzy" is 0.8 by default. 
https://github.com/DenisCarriere/geocoder/blob/16a697240974b2cb66df56b534be43ef26218110/geocoder/geonames.py#L93

Is there some reasoning behind this value?

The Geonames' docs say:
http://www.geonames.org/export/geonames-search.html

>default is '1', defines the fuzziness of the search terms. float between 0 and 1. The search term is only applied to the name attribute.

Perhaps it is better to use the defaults suggested by the service documentation?

* * *

I probably wouldn't raise this issue if Geonames' idea of fuzziness wasn't about messing up search result relevance. For example, if I search for "Russia" with Geocoder's current defaults:

```
g = geocoder.geonames('Russia', key='KEY')
g.geojson
```

I will get a region in Jamaica called "Russia". However, as a user I would prefer to see countries first and regions second, but "fuzzy" interferes with result relevance. This behavior is easy to replicate without Geocoder by manually altering search query in the URL:

http://www.geonames.org/search.html?q=russia&country=&fuzzy=0.8

This is definitely not the package maintainers' fault, but since Geonames service doesn't do fuzziness right, perhaps it's a good idea to set fuzzy to 1.0, as their docs suggest?

**Comment by ebreton** [comment]
I agree. We should follow Geoname's best practice.

Would you mind create a PR to change the default value ?

**Comment by paramono** [comment]
@ebreton Sure, no problem, will do.

Also, I asked on geonames' forum about the issue with fuzziness, got no reply yet. 
http://forum.geonames.org/gforum/posts/list/35043.page
