### ISSUE TITLE
freegeoip __deprecation_message__; deadline July 1st, 2018

### ISSUE THREAD

**Issue by 1fish2** [DenisCarriere/geocoder#350]
From a command like

> geocode --provider freegeoip 138.197.111.108

the output includes the key/value pair:

`"__deprecation_message__": "This API endpoint is deprecated and will stop working on July 1st, 2018. For more information please visit: https://github.com/apilayer/freegeoip#readme"`

In addition to API changes, [the new readme](https://github.com/apilayer/freegeoip#readme) says free accounts will be able to access up to 10,000 requests per month, not per hour.

**Comment by ebreton** [comment]
Thanks for letting us know @1fish2 ! 👍 

I have updated the README consequently. Please feel free to make another PR if you feel it deserves more !

Manu
