### ISSUE TITLE
ModuleNotFoundError: No module named 'ratelim'

### ISSUE THREAD

**Issue by grekichi** [DenisCarriere/geocoder#460]
Hi there !
I tried to use geocoder.google(~, method='reverse').
It happened this error. for detail below,
~ geocoder/freegeoip.py", line 8, in <module> ~
Should I install 'retelim' also for using geocoder ?

**Comment by vihaanmody1** [comment]
If it tells you this, you should install 'retelim'. If it doesn't work, reinstall geocoder.

**Comment by grekichi** [comment]
Thanks for communication, Vihaan.

I tried install retelim and the other modules.
But 'geocoder.google' could not run.
Isn't it need to register google API ?

So I tried 'geocoder.osm', and it worked !

**Comment by vihaanmody1** [comment]
Nice to hear that the problem is fixed. Please close this issue.
