### ISSUE TITLE
Store multiple results with Bing and others

### ISSUE THREAD

**Issue by DenisCarriere** [DenisCarriere/geocoder#59]

**Comment by DenisCarriere** [comment]
Question from Twitter:

[@spatialaustin](https://twitter.com/spatialaustin) [@DenisCarriere](https://twitter.com/DenisCarriere) love the geocoder. Is it possible to handle multiple results for a location lookup?

https://twitter.com/spatialaustin/status/562346047502942208

**Comment by stirringhalo** [comment]
I'm very interested in this too, looking to have about 5 results from each forward geocoder as the first result sometimes isn't the best. Anything I can do to help?

**Comment by DenisCarriere** [comment]
@stirringhalo This one is a tricky one, because the entire code needs to change or I need to build a container that holds multiple different "geocode" objects. When it was first built I didn't have this in mind and now it's a pain to correct :(

**Comment by jdanlewis** [comment]
+1 This would be a great feature.

**Comment by khuumi** [comment]
This would be very useful!

**Comment by ebreton** [comment]
5 providers will support multi results after the merge of PR #264 
- list will be found in README
- dedicated page in the documentation to describe how to access the results

**Comment by DenisCarriere** [comment]
👍 Looks great for the multi-result. Just need to add `maxRows` as a param.
