### ISSUE TITLE
Command Line utility

### ISSUE THREAD

**Issue by themiurgo** [DenisCarriere/geocoder#70]
Would a command-line utility be useful? For my research I often need to geocode many addresses, usually in tabular format, so it would be excellent to have something like this, that accepts input as filenames or from STDIN.

    $ geocode myfile.txt google
    # Full json response, one json document per line
    ...
    $ cat myfile.txt | geocode osm
    # Full json response, one json document per line
    ...

Receiving a json response rather than selected fields is convenient, as it keeps the complexities associated to the document schemas (which are different for each service) out of the utility. The json responses can later be parsed easily, for instance with utilities like jq.

    $ cat myfile.txt | geocode google | jq [.lat,.lng,.country] -c
    [37.4219985,-122.0839544,"United States"]
    ...

As I need it for my work, I can take care of developing this utility. Do you think this might be useful for the project?

**Comment by themiurgo** [comment]
This is broken at the moment.

    $ cat foo.txt
    Boston, MA
    Ontario
    $ cat foo.txt | geocode

**Comment by DenisCarriere** [comment]
Thanks for noticing that, I've found a quick little fix that will do the job, I'm incorporating it today.

```python
import fileinput
for line in fileinput.input():
        print(line)
```

**Comment by themiurgo** [comment]
Thanks a lot, you have such quick responses! :)

**Comment by DenisCarriere** [comment]
@themiurgo This fix seems to work for me, try it out and let me know if that works out.

**Comment by themiurgo** [comment]
Yes, works perfectly! :+1:
