### ISSUE TITLE
Command Line tests

### ISSUE THREAD

**Issue by themiurgo** [DenisCarriere/geocoder#72]
Need to implement some basic CLI tests.

**Comment by ebreton** [comment]
test_cli.py validates the basics of the CLI. 
dedicated test_[provider].py files validate the geocoding functionalities more thoroughly

I guess we can close this issue. What do you think @DenisCarriere  ?

**Comment by DenisCarriere** [comment]
Yep! We've added some basic CLI, everything can be improved but at this stage the CLI part is being tested.
