### ISSUE TITLE
Cache / Memoization

### ISSUE THREAD

**Issue by themiurgo** [DenisCarriere/geocoder#73]
A useful addition, especially when converting a large number of strings, would be to store/cache the results to some common strings somewhere (memory, mongodb database, redis, ...). I'm not sure what's the best way to do this to be generic enough. I had used a mongodb in my old geocoder and it worked well
https://gist.github.com/themiurgo/3136205

However I'd like it to be more generic for this module. I'll think about it.

**Comment by DenisCarriere** [comment]
Ok I am going tho attempt adding this caching feature in the Geocoder.

The CLI would look something like this:

**Simple Case**

```bash
$ geocode "Ottawa ON" --cache
```

**Batch geocode**
```bash
# Linux
$ cat "foo.txt" | geocode --cache
```
```bash
# Windows
C:\> type "foo.txt" | geocode --cache
```


**Extra parameters**
```bash
$ geocode "Ottawa ON" --provider "google" \
                      --cache "geocoder" \
                      --db "mongodb" \
                      --username "Denis" \
                      --password "Password"
```

**Using it in Python**

```python
>>> import geocoder
>>> g = geocoder.google("Ottawa ON", cache=True)
>>> g.json
{...}
```

**Extra parameters**

```python
>>> g = geocoder.google("Ottawa ON",
                        cache="geocoder",
                        db="mongodb",
                        username="Denis",
                        password="Password")
```

**Comment by DenisCarriere** [comment]
Started writing the documentation before the code, I think it's easier that way to clearly define how it's going to work, @themiurgo let me know what you think.

https://github.com/DenisCarriere/geocoder/blob/master/docs/features/Caching.md

**Comment by themiurgo** [comment]
Great Denis! These are the two concerns I have at this time:

- Do we really need mongodb? This would mean you cannot have cache unless you have mongodb (bad). We could simply Python memory, although it's going to be less memory efficient and will eat a lot of RAM when geocoding large instances. We could also use sqlite, that is included in the standard library and would not require additional parameters. Not sure what makes more sense.
- What's more expectable? That cache to be turned on by default or not? If we can set-up an inexpensive cache (inapt? sqlite?) that doesn't need any parameter / additional requirements, then cache could be turned-on by default.

Just brainstorming. Let me know of what you think about these issues.

**Comment by DenisCarriere** [comment]
Good points, I've talked to a few other people about this and it might be better to do in memory and/or SQLite since you don't actually have to set up a database server.

Right now I'm also just brainstorming.. :) I might want to add SQLAlchemy as a dependency since it's really good library to make the code look cleaner and more efficient.

**Comment by DenisCarriere** [comment]
@themiurgo I'm almost finished the **Cache feature**, now I just need to incorporate it in the Base.py code, it's a pretty clean minimal code and works pretty good with lots of options for future expansion & testing.

## Goal
To embed the caching feature without adding any parameters in the geocoder, the database default will be `sqlite:///:memory:`, the cache will stay alive until the Python is closed, the CLI would have to pass a database parameter to have this feature (Ex: `db=sqlite:///geocoder.db`).

|Params   |Description       |Default            |
|:--------|:-----------------|:------------------|
|db       |SQLAlchemy DB    |sqlite:///:memory: |
|location |Query Location    |                   |
|provider |Geocoder Provider |bing               |
|method   |Geocoder Method   |geocode            |
|output   |json/geojson/osm  |json               |

**Python code: [cache.py](https://github.com/DenisCarriere/geocoder/blob/master/geocoder/cache.py)**

## How-To

```python
import geocoder
from cache import Cache

# User Variables
location = 'Orleans, Ottawa'

# Geocode Address
g = geocoder.bing(location)

# Create Cache Databse
cache = Cache('sqlite:///:memory:')

# Insert into Database
cache.insert(g)

# Find results with a Query
out = cache.find(location, output='json')
print(out)
```

**Comment by themiurgo** [comment]
This looks great, Denis! The only thing I would change is the non-persisentcy of the cache. If it's on a SQLite file, we might as well keep it there, what do you think? That way we can have cache between repeated calls of geocoder, saving requests!

**Comment by DenisCarriere** [comment]
Save the cache.py
https://gist.github.com/DenisCarriere/b174f10d7a309d001026

**Comment by yagermadden** [comment]
just testing

**Comment by DenisCarriere** [comment]
Great idea, however it's outside of the scope, will not be implementing.

**Comment by themiurgo** [comment]
Probably a good decision to keep the codebase clean and consistent. 👍

**Comment by DenisCarriere** [comment]
Agreed! :+1: I've written some custom caches as an external tools, it's a lot better to have it separated from the codebase.

**Comment by themiurgo** [comment]
@DenisCarriere Care to share them, even as gists, or to open a new repo? They might be useful for the community. :)

**Comment by DenisCarriere** [comment]
@themiurgo It was sloppy code :) essentially it was just a dictionary stored in memory and the address was the key with an `if` statement looking up for the key before executing the geocode.
