### ISSUE TITLE
Google Client ID & Private Key

### ISSUE THREAD

**Issue by DenisCarriere** [DenisCarriere/geocoder#99]
Request from Pedro Mesquita:
As for google client ID & Private key i was asking where i can put on geocode api. Is this valid : 
```python
geocoder.google(
   '41.1474794 -8.55558',
   client_id="myclientid", 
   private_key="myprivatekey", 
   method='reverse')
```

Another Request from Dark Hado

I'm trying your geocoder but i cant find where i can put my enterprise account from Google in. For example on geocoder:  
```python
>>> ggeocoder.Geocoder(client_id="myclientid", private_key="myprivatekey)
>>> g = ggeocoder.Geocoder()
>>> results = g.reverse_geocode(lat,long)
```
can you help me out?

**Comment by PedroMesquita** [comment]
geocoder.google(
   '41.1474794 -8.55558',
   client_id="myclientid", 
   private_key="myprivatekey", 
   method='reverse',
   short_name=False)

That's it Denis !!!! It would be great to incorporate this in the next revision. geocoder  Rocks :+1:

**Comment by DenisCarriere** [comment]
Pedro, are you talking about the Free API key or the "Google Maps API for Work".
**Google Maps For work**
https://developers.google.com/maps/documentation/business/webservices/auth
**Free API**
https://developers.google.com/maps/documentation/geocoding/#api_key

The Free API key works now.

Install a new version of Geocoder using the latest of Github.
```bash
$ git clone https://github.com/DenisCarriere/geocoder.git
$ cd geocoder
$ sudo python setup.py install
```
Then you can use your API key when calling the geocoder with the param: `key`
```python
>>> import geocoder
>>> g = geocoder.google("41.1474794 -8.55558", key="<API KEY>", method="reverse")
...
```
Let me know if it works!

**Comment by PedroMesquita** [comment]
Hi Denis

No. I'm talking about this:
https://developers.google.com/maps/documentation/business/webservices/auth


Python Example of ggeocoder?

def georev(lat,long):
    try:
        g = ggeocoder.Geocoder(client_id="ClientID", private_key="MyPrivateKey")
        g = ggeocoder.Geocoder()
        results = g.reverse_geocode(lat,long)
        return results
    except Exception as cgex:
        print str(cgex)

Ugly C# example
------------------------------------------
const string keyString = "MyPrivateKey";// "YOUR_PRIVATE_KEY";
string urlString = "http://maps.googleapis.com/maps/api/geocode/json?latlng="
+ coordinate.Latitude.Replace(',','.') + "," +
coordinate.Longitude.Replace(',','.') + "&sensor=true&client=MyClientID";//
"YOUR_URL_TO_SIGN";

string url = GoogleSignedUrl.Sign(urlString, keyString);

WebClient webclient = new WebClient();

string var = "";
try
{
var = webclient.DownloadString(url);
}
catch (Exception ex)
{
...
}
---------------------------------------

2015-01-08 21:54 GMT+00:00 Denis <notifications@github.com>:

**Comment by Chartres** [comment]
There's an example (in Python) at Google Developers on how to perform the signing:
https://developers.google.com/maps/documentation/business/webservices/auth#signature_examples

```python 
...
return original_url + "&signature=" + encoded_signature
```
It can probably be added as a function to `google.py` but still have to think about it a bit, because the final url is being generated later on in `base.py`...
